% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name quadMin_gd
%  @associatedFile /MATLAB Drive/quadMin_gd.m
%  @mostRecentlyActioned true
%  @uniqueId 1282A8AE

quadMin_gd

%% @name quadMin_gd
%  @associatedFile /MATLAB Drive/matp hw1/quadMin_gd.m
%  @mostRecentlyActioned true
%  @uniqueId A20884FA

quadMin_gd

%% @name quadMin_cg
%  @associatedFile /MATLAB Drive/matp hw3/quadMin_cg.m
%  @mostRecentlyActioned true
%  @uniqueId 0ABC4A9E

quadMin_cg

%% @name pcg_linsolv
%  @associatedFile /MATLAB Drive/matp hw3/pcg_linsolv.m
%  @mostRecentlyActioned true
%  @uniqueId AB253F58

pcg_linsolv

%% @name pcg_linsolv_2
%  @associatedFile /MATLAB Drive/matp hw3/pcg_linsolv.m
%  @mostRecentlyActioned false
%  @uniqueId D5F5C5C3

pcg_linsolv(C, r)

%% @name quadMin_pcg
%  @associatedFile /MATLAB Drive/matp hw3/quadMin_pcg.m
%  @mostRecentlyActioned true
%  @uniqueId 2B2F86A5

quadMin_pcg

%% @name quadMin_BB
%  @associatedFile /MATLAB Drive/code_hw4/quadMin_BB.m
%  @mostRecentlyActioned true
%  @uniqueId 2756DBC3

quadMin_BB

%% @name quadMin_BB_2
%  @associatedFile /MATLAB Drive/code_hw4/quadMin_BB.m
%  @mostRecentlyActioned false
%  @uniqueId 1578C47A

quadMin_BB(A, b, x0, tol)

%% @name quadMin_DFP
%  @associatedFile /MATLAB Drive/code_hw4/quadMin_DFP.m
%  @mostRecentlyActioned true
%  @uniqueId 14534731

quadMin_DFP

%% @name test_penalty_qp
%  @associatedFile /MATLAB Drive/code_hw6/test_penalty_qp.m
%  @mostRecentlyActioned true
%  @uniqueId 849E7D70

test_penalty_qp

%% @name penalty_qp
%  @associatedFile /MATLAB Drive/code_hw6/penalty_qp.m
%  @mostRecentlyActioned true
%  @uniqueId 2F5F97DF

penalty_qp

%% @name ALM_SVM_s
%  @associatedFile /MATLAB Drive/code/ALM_SVM_s.m
%  @mostRecentlyActioned true
%  @uniqueId 8C6EBED5

ALM_SVM_s

%% @name ALM_SVM_s_2
%  @associatedFile /MATLAB Drive/code/ALM_SVM_s.m
%  @mostRecentlyActioned false
%  @uniqueId D52655F4

ALM_SVM_s(X, y, lam, opts)

%% @name test_model_SVM_rho02
%  @associatedFile /MATLAB Drive/code/test_model_SVM_rho02.m
%  @mostRecentlyActioned true
%  @uniqueId 045935D5

test_model_SVM_rho02

